### ISSUE TITLE
Poly-fill and web-demo for FLIF

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#21]
I have created a poly-fill / playground for FLIF, using emscripten.

[Code](https://github.com/UprootLabs/poly-flif)

[Demo](https://uprootlabs.github.io/poly-flif/)

~~It's not perfect; there is a memory leak..~~ Solved.

Feedback welcome!

**Comment by ssbssa** [comment]
I've found and fixed a few memory leaks.
You can find them here: [no-leaks](https://github.com/ssbssa/FLIF/tree/no-leaks)

**Comment by hrj** [comment]
@ssbssa Great; thanks for the heads up! Will wait for merge with upstream.

**Comment by jonsneyers** [comment]
Cool!

**Comment by hrj** [comment]
I have implemented lazy loading of images in [the demo](https://uprootlabs.github.io/poly-flif/). Which means, we can now:

* add many more images in the show-case
* add PNGs for comparison (as per your request @jonsneyers )

**Comment by heavyk** [comment]
really cool! sometimes I still get out of memory errors though. perhaps that's old code because I don't see more images or comparison pngs either?

still, it's pretty awesome that the monkey at 40% stream is already very very good quality. if it were used as a lossy encoder (chopping the end off the file) it still makes very good images!

**Comment by hrj** [comment]
> perhaps that's old code because I don't see more images or comparison pngs either?

Oh, I haven't implemented it yet. Was just noting that we *are able to* take it up now.

I wonder what is the best way to render truncated PNGs in the comparison. Letting the browser do it natively will be faster, but will probably give different results on different browsers. I will use the lib-png embedded in emscripten for now.

**Comment by hrj** [comment]
Update: Implemented truncated PNG comparison. I am using browser's native rendering of PNGs for now.

Also, the demo now shows file-sizes (truncated and original).

**Comment by jonsneyers** [comment]
:+1:

**Comment by hrj** [comment]
Updates:

* Fixed memory leak, thanks to @ssbssa 
* Removed filesystem emulation from JS; the JS code is now 296 kB. (90kB after gzip)

Will be trying to further reduce JS code size.

**Comment by hrj** [comment]
Some more size crunching: Eliminated IO calls, used `-Oz` instead of `-O3` and enabled closure compiler. 

The size of JS is now 217kB (68kB after gzip)!

Time to move onto animation support!

**Comment by mrdoob** [comment]
Seems like colors get darkened at the moment? (Chrome 45, OSX 10.10.4)

![screen shot 2015-10-07 at 15 59 22](https://cloud.githubusercontent.com/assets/97088/10349427/763f3a00-6d0c-11e5-8d09-23225e88d59f.png)

**Comment by hrj** [comment]
@mrdoob Yeah, the PNG is being decoded directly by the browser, which means it gets gamma correction, etc. One idea is to strip the gamma information from the demo PNGs https://github.com/UprootLabs/poly-flif/issues/7

In other news,
* I got animations working. Cleaning up and committing pending.
* @mrdoob is here, whoa!

**Comment by mrdoob** [comment]
> One idea is to strip the gamma information from the demo PNGs UprootLabs/poly-flif#7

Yeah, it makes FLIF look incorrect otherwise....

> @mrdoob is here, whoa!

Since day one! 😀

**Comment by hrj** [comment]
Update:

* Added animation support to the demo. All frames in the source are decoded together and then played back in a loop. The playback is fast, but the decoding needs more work.
* Stripped the `gamma` info from PNGs in the demo. Please let me know if that fixes the colors in the comparison.
* JS size remains almost the same. However, I realised that there is a separate memory layout file created by emscripten, which needs to be accounted for. This file contains global data declared in the C++ code. It was 16KB to begin with. @sipa removed a lookup-table and the size was reduced by 1KB. There is one more 8KB table which can [perhaps be nuked](https://github.com/FLIF-hub/FLIF/issues/66).

**Comment by heavyk** [comment]
yea it locks up the interface a bit, but dude, that's freakin awesome!

still can't believe how good those look even at 40% stream.

can decoding be done in parallel?

**Comment by hrj** [comment]
Hey @heavyk, thanks!

> can decoding be done in parallel?

You mean at JS level? Yeah, with Web Workers.

**Comment by mrdoob** [comment]
> Stripped the gamma info from PNGs in the demo. Please let me know if that fixes the colors in the comparison.

Yep! Fixed it.

> Added animation support to the demo. All frames in the source are decoded together and then played back in a loop. The playback is fast, but the decoding needs more work.

Looking good! Albeit with some glitches...

![screen shot 2015-10-08 at 11 48 05](https://cloud.githubusercontent.com/assets/97088/10371730/c0906a56-6db2-11e5-826b-763ac452d19b.png)

**Comment by jonsneyers** [comment]
This partial decode glitch is probably caused by the FRA transform, use flif --lookback=0 while encoding to avoid the issue.

**Comment by hrj** [comment]
@jonsneyers Is it an artifact of https://github.com/FLIF-hub/FLIF/issues/67 ? If so, I think I will wait for a fix (since you have labelled it a bug), rather than re-encoding with a workaround.

**Comment by jonsneyers** [comment]
Yes. The easy fix is to disable FRA for now ;)
Implementing FRA as another channel is a bit of work.

**Comment by hrj** [comment]
Updates:

* Animation alpha glitch (#67) fixed by @jonsneyers 
* Couple of other fixes from upstream
* Added option to compare with original image
* Added option to compare with JPEG for still images without transparency
* JS size is now 53KB gzipped.

**Comment by blixt** [comment]
This is amazing! You should either disable upsampling on the PNG or enable it for the FLIF one, so that they can be compared more equally (for us retina users :).

![screen shot 2015-10-21 at 11 33 50 am](https://cloud.githubusercontent.com/assets/158591/10641595/dcee4c88-77e7-11e5-9db8-da918e007678.png)

**Comment by hrj** [comment]
On Wed, Oct 21, 2015 at 9:05 PM, Blixt <notifications@github.com> wrote:

> You should either disable upsampling on the PNG or enable it for the FLIF
> one, so that they can be compared more equally (for us retina users :).


​Ah, finally a retina user! There's an open issue for this; can you please
answer my questions there
<https://github.com/UprootLabs/poly-flif/issues/10>​ ?

**Comment by hrj** [comment]
Update! I have separated out the demo from the decoder. It should be now possible to use the JS decoder as a library in any website.

As a convenience, the library automatically detects `<canvas>` elements and renders FLIF images to them if they have a specific attribute. Hence, for most use cases, there is no need to write additional JS. There is also a programmatic API if desired. [Details](https://uprootlabs.github.io/poly-flif/api.html) and [demo](https://uprootlabs.github.io/poly-flif/polyflif-sample.html).

The JS payload is about 50 to 80KB gzipped. (Keeps varying as I change the code). It can be downloaded from the [release page](https://github.com/UprootLabs/poly-flif/releases) on Github. In the future we could make it available via a CDN so that it can be cached across websites.

**Comment by hrj** [comment]
Update: released PolyFLIF [version 0.3](https://github.com/UprootLabs/poly-flif/releases/tag/v0.3). This is the first release after finalization of the FLIF16 bitstream format.

I am gonna close this issue now. Thanks for all the feedback everyone. Please watch the project or subscribe to RSS feed of releases for further updates.
